
//メインの画面に使われるサイドメニューの部品
//多くのところで同じものを使うので構造体にしている


import Foundation
import UIKit

struct sideBar {
    //半透明のViewと、画面遷移ボタンが貼られるscrollView
    static let sideView1 = UIView()
    static let sideView2 = UIView()
    static let sideScrollView = UIScrollView()
    static let color = UIColor(red: 0, green: 0, blue: 0, alpha: 0.5)
    //サイドビュー用部品
    static let mView1 = UIView()
    static let mView2 = UIView()
    static let mView3 = UIView()
    static let mView4 = UIView()
    static let mView5 = UIView()
    static let mView6 = UIView()
    static let mView7 = UIView()
    static let mView8 = UIView()
    static let mView9 = UIView()
    static let mView10 = UIView()
    static let mView11 = UIView()
    static let mView12 = UIView()
    static let mView13 = UIView()
    //画面左側に表示しているアイコン？
    static let mimage1 = UIImage(named: "bt1")
    static let mimage2 = UIImage(named: "bt2")
    static let mimage3 = UIImage(named: "bt3")
    static let mimage4 = UIImage(named: "bt4")
    static let mimage5 = UIImage(named: "bt5")
    static let mimage6 = UIImage(named: "bt6")
    static let mimage7 = UIImage(named: "bt7")
    static let mimage8 = UIImage(named: "bt8")
    static let mimage9 = UIImage(named: "bt9")
    static let mimage10 = UIImage(named: "bt10")
    static let mimage11 = UIImage(named: "bt11")
    static let mimage12 = UIImage(named: "bt12")
    static let mimage13 = UIImage(named: "bt13")
    //mimageを貼るimageView
    static let mimageView1 = UIImageView()
    static let mimageView2 = UIImageView()
    static let mimageView3 = UIImageView()
    static let mimageView4 = UIImageView()
    static let mimageView5 = UIImageView()
    static let mimageView6 = UIImageView()
    static let mimageView7 = UIImageView()
    static let mimageView8 = UIImageView()
    static let mimageView9 = UIImageView()
    static let mimageView10 = UIImageView()
    static let mimageView11 = UIImageView()
    static let mimageView12 = UIImageView()
    static let mimageView13 = UIImageView()
    //画面遷移用ボタン
    static let mbutton1 = UIButton()
    static let mbutton2 = UIButton()
    static let mbutton3 = UIButton()
    static let mbutton4 = UIButton()
    static let mbutton5 = UIButton()
    static let mbutton6 = UIButton()
    static let mbutton7 = UIButton()
    static let mbutton8 = UIButton()
    static let mbutton9 = UIButton()
    static let mbutton10 = UIButton()
    static let mbutton11 = UIButton()
    static let mbutton12 = UIButton()
    static let mbutton13 = UIButton()
    //仕切り用View
    static let lineView1 = UIView()
    static let lineView2 = UIView()
    static let lineView3 = UIView()
    static let lineView4 = UIView()
    static let lineView5 = UIView()
    static let lineView6 = UIView()
    static let lineView7 = UIView()
    static let lineView8 = UIView()
    static let lineView9 = UIView()
    static let lineView10 = UIView()
    static let lineView11 = UIView()
    static let lineView12 = UIView()
    static let lineView13 = UIView()
    //サイドメニューの頭の方の部品
    static let text1 = UILabel()
    static let text2 = UILabel()
    static let imageView1 = UIButton()
    static let imageView = UIImageView()
    static let sideimage1 = UIImage(named: "mokume")
    static let sideimage2 = UIImage(named: "p.no")
    //サイドメニュー後ろの方の部品
    static let noSpace = UIButton()
    static let backButton = UIButton()
    static let subButton1 = UIButton()
    static let subButton2 = UIButton()
    static let subButton3 = UIButton()
    static let subImage1 = UIImage(named: "bt14")
    static let subImage2 = UIImage(named: "bt15")
    static let subImage3 = UIImage(named: "bt16")
    
}
